---
title: "Project 1"
author: "Roy Wu"
date: "07/05/2021"
output: github_document
---
```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```


####Data Cleaning
Import packages  
```{r, include = TRUE}
library(tidyverse)
library(stargazer)
library(haven)
```

Import the Dataset
```{r}
CRIME2 <- read_dta("~/Documents/University/\U0001f4c8ECON 3740 /Data Sets- STATA/CRIME2.DTA")
```

Filter out the 1987 and 1982 dataset separately

```{r}
year87 <- filter(CRIME2, d87==1)
year82 <- filter(CRIME2, d87==0)
```

Add crime rates in 1982 (crmrte82) to the 'year87' dataset as an independent variable 'crmrte82'Rename crime rates in 1987 to 'crmrte87'

```{r}
year87 <- 
  mutate(year87,
         crmrte82 = year82$crmrte,
         crmrte87 = year87$crmrte,
         lcrmrte82 = year82$lcrmrte,
         lcrmrte87 = year87$lcrmrte)
```

####Model 1
```{r}
model_1 <- lm(crmrte87 ~ pcinc + lawexpc + pop + unem + crmrte82, year87)
summary(model_1)
```
```{r}
plot(model_1)
```

####Model 2
```{r}
model_2 <- lm(lcrmrte87 ~ unem + llawexpc + lcrmrte82, year87)
summary(model_2)
plot(model_2)
```




####Model 3
```{r}
model_3 <- lm(crmrte87 ~ pcinc + lawexpc + pop + unem, year87)
summary(model_3)
plot(model_3)
```
####Model 4
```{r}
model_4 <- lm(lcrmrte87 ~ unem + llawexpc, year87)
summary(model_4)
plot(model_4)
```
####Results
```{r}
stargazer(model_1, model_2,model_3,model_4, type= "text",title="Regression Results",
          no.space=FALSE,
          align = FALSE) 

```

